import time

#game

print ("Welcome to Average Life The Game!\n")

time.sleep (4)

print ("The objective of this game is to make it through one day of life without anything going horribly wrong.\n")
print ("Age: 38")
print ("Sex: Male")
print ("Marital Status: Single\n")
time.sleep(4)
print("You are sad, reckless, boring, and have a history of being average.")
print ("You are sick of being average...")
time.sleep(2)
question0= str(input("Are you ready to change your average life? [Y/N]: \n"))
if question0 in["y"]:
    print ("Soo, you wake up feeling sweaty...\n")
    print ("You realize that the A/C is not running like it was last night. You can't fathom why it wouldn't be working so you head downstairs to the A/C unit.\n")
    time.sleep(4)
    print ("You examine the A/C unit and notice wires hanging out and into the wet grass. What could have caused this damage?!\n")
    question1= str(input("Do you avoid examining the wires? [Y/N]: \n"))
    if question1 in["y"]: #you avoid examining wires
        print ("You begin to smell something cooking...\n")
        time.sleep(3)
        question2= str(input("Do you follow the smell? [Y/N]: "))
        if question2 in["y"]: #you follow smell and fail game
            print ("You blindly follow the smell and step onto something warm...")
            time.sleep(4)
            print("Something soft...\n")
            time.sleep(3)
            print ("You look down and see a dead raccoon!!\n")
            time.sleep(2)
            print ("You shard yourself because of the excitment and quickly hurry inside to change your clothes before calling the repair man.")
            print ("The repair ma tells you that he will be coming in at 11 o'clock and you must be there to let him in.")
            print ("Because of this you are unable to attend work today and call in sick.\n")
            time.sleep(5)
            print ("It does not go well with your boss and you found yourself fired.")
            print ("This throws you into an angry fit so you hop into your car and begin to speed.")
            print ("You begin running reds and swerving around traffic...")
            time.sleep(8)
            print ("BAM!")
            time.sleep(5)
            print ("You smack into a minivan!\n")
            time.sleep(3)
            print ("YOU DIE")
        else: #if you don't follow smell
            print ("You give up on the situation and proceed to eat breakfast before heading out to work.\n")
            time.sleep(2)
            print ("It could have been worse right?\n")
            time.sleep(1)
            print ("At least you didn't accidentally kill yourself or something...")
            time.sleep(2)
            print ("After 20 minutes in traffic on the 405 you're running late and getting frustrated with the drivers around you.")
            print ("You see a clean open shoulder lane and dream about jumping in and passing all the drivers.")
            question3= str(input("Do you illegally jump into the shoulder lane? [Y/N]: \n"))
            if question3 in["y"]:#jump in shoulder lane
                print ("You jump into the shoulder and floor it. The sound of your 4 cylinder engine rumbles as you speed past angry drivers.\n")
                print ("You see your exit approaching so you force your way through 5 lanes of traffic safely and make it to work 1 minute early")
                print ("You walk in with a smile prompting your coworkers to ask you what's up with your grin.")
                question4= str(input("Choose 1 to tell them about your genius recklessness. Choose 2 to make up a lie: \n"))
                if question4 in["1"]:#tell about jumping in shoulder
                    print ("You tell them about how you cheated traffic this morning and they gasp at you knowing that you are not one to be risky.")
                    print ("Your boss walks in an hears your coworkers cheering you on about this situation and kindly asks you to step into his office.")
                    print ("He tells you that he has been considering you as a cadidate for a promotion but that he wants to ask you one question first.")
                    print ("You immediately begin to sweat again")
                    time.sleep(4)
                    print ("He asks you what it means to take the integral of a curve.")
                    print ("[1] for area above the curve, [2] for area under curve, [3] for why you asking me?!")
                    question5=str(input("You think hard...: \n"))
                    if question5 in["2"]: #answer calculus right
                        print ("Your boss congratulates you on the promotion. Your face lights up with joy!")
                        print ("You get a raise of $10,000 and get the day off work\n")
                        print ("You run out the office and immediately decide to treat yourself to an amazing lunch at the diner down the street.")
                        time.sleep(3)
                        print("You go into the diner and sit down. A pretty woman walks past you and sits down at the bar. You remember how lonely you are.")
                        print ("You notice that she looks at you.\n")
                        question6= str(input("Do you go sit next to her or mind your business? [1/2]: \n"))
                        if question6 in["2"]:#waiter or girl
                            print("You stay seated and wait for the waiter to approach you.")
                            print ("The waiter approaches and you order an amazing grilled cheese sandwhich with mac n cheese.")
                            print("You leave the establishment feeling satisfied.\n")
                            print("You get into you car and drive home to enjoy a relaxing day watching TV")
                            print("On your drive home you remember that you forgot to call the repair man about the A/C so you call him from your car.")
                            print("He tells you that he will be there when you arrive.\n")
                            print ("You arrive home and see the repair man arriving at the same time.")
                            print("He greets you and easily fixes your A/C unit")
                            print ("You sit down and begin flipping channels")
                            question7=str(input("Do you watch 1.Basketball, 2.Cartoon Network, or 3.The News?: \n"))
                            if question7 in["1"]:
                                print ("You enjoy an exciting basketball game where your team wins in the last seconds.\n")
                                time.sleep(3)
                                print("Congratulations! You beat the game!")
                            elif question7 in["2"]:
                                print("You watch a hilarious episode of Rick and Morty and laugh yourself to sleep on the couch.\n")
                                time.sleep(3)
                                print ("Congratulations! You beat the game!")
                            elif question7 in["3"]:
                                print ("You watch the news and see a report that the company you work for has inceased sales this increasing stock price")
                                print("You smile to yourself and think about how you got promoted today.\n")
                                print("Suddenly breaking news flashes and you see that there is a manhunt for a killer in your neighborhood.\n")
                                print("You hear something in the bushes outside your house...")
                                time.sleep(4)
                                print("You are scared but you get a knife from the kitchen and go outside to look")
                                print("You use your phone as a flashlight and nervously scan your backyard")
                                print("You hear something behind you!\n")
                                time.sleep(5)
                                print("You turn around and are jumped on by something big. Your knife falls out of your hand. You scream like a girl.\n")
                                time.sleep(4)
                                print("To your surprise you are not dead.")
                                print("You feel yourself being licked by something wet and open your eyes to see your neighbors dog")
                                print("You burst into a laugh and return the dog to the neighbor. She thanks you and offers you cookies.\n")
                                bonus_ending= str(input("Do you accept the offer? Y/N: \n"))
                                if bonus_ending in["y"]:
                                    print("You go inside and she takes out cookies from the oven.\n")
                                    print("You talk with her and explain how crazy your day was and how you beat traffic today.")
                                    time.sleep(3)
                                    print("She thinks you're not so lame and offers up her number.")
                                    print("You put it in your phone without hesitation and you leave the house with a bag of fresh sugar cookies.\n")
                                    print("You think to yourself that maybe life won't be so lonely anymore")
                                    print("Today was a good day, hopefully tomorrow will be too...\n")
                                    time.sleep(4)
                                    print("CONGRATULATIONS ON FINISHING THE GAME AND AQUIRING THE BONUS PATH!!\n")
                                    time.sleep(5)
                                    print("\n")
                                    print ("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
                                    print ("WRITTEN AND CODED BY ALEXANDER NAROUZ")
                                    print ("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
                                elif bonus_ending in["n"]:
                                    print("You give her the dog and she smiles at you. You walk back to your house.")
                                    print("Something tells you should taken those cookies.")
                                    print("You think about going back.\n")
                                    time.sleep(3)
                                    print("It's too late. You are on your way home right?")
                                    print("Yea...it's too late. Maybe next time.\n")
                                    print("You lay in your bed feeling sad for yourself but then you remind yourself about how good today was.")
                                    time.sleep(3)
                                    print("Congratulations on beating the game!! Replay to find what you missed out on.")
                                                      
                            else:
                                print("You were so close. RIP to you.")
                            
                                
                        else:
                            print("You feel a massive force standing behind you.")
                            time.sleep(4)
                            print ("You turn around and see a burly man towering over you. He looks angry.\n")
                            print ("He asks you what your problem is and you begin to insist there is no problem")
                            print ("You get up and begin to walk away when suddenly everything goes dark.\n")
                            print ("You wake up in the hospital with your parents next to you.")
                            time.sleep(3)
                            print ("How did your parents get here? They were supposed to be in Ohio.")
                            print ("The doctor walks into the room and explains that you have been in a coma for 2 years because of a concussion.")
                            print ("Your parents begin to cry while you look around the room confused.\n")
                            print ("GAME OVER")
                    else:#failed calc question
                        print ("Your boss looks at you disappointed and aks you to pack your things and never return to the office.")
                        print ("You get violently angry and punch you boss in the face and begin to pummel him.\n")
                        print ("Your coworkers call the police on you and you are arrested and never heard of again.")
                        time.sleep(5)
                        print("GAME OVER")
                else:#lie about happiness and fail
                    print("Your boss walks into the room before you get a chance to speak and asks you to enter into his office")
                    print ("He tells you that he has been considering you as a cadidate for a promotion.")
                    print ("He tells you that be believes that your are not comfortable working at this office and suggests you find a new job.\n")
                    print ("You are flaberghasted by this and ask him to explain. He tells you that you frequently lie to coworkers.")
                    print ("He believes that there is tension between you and the rest of the staff so he would like you leave.\n")
                    print("You break into tears and get inside your car")
                    print ("You begin driving like a maniac.")
                    print("Suddenly you hear police sirens and a man over a megaphone asks you to pull over...")
                    time.sleep(3)
                    print ("You pull over and begin to sob on the steering wheel.")
                    print("The officer arrests you.\n")
                    time.sleep (4)
                    print ("Because of your criminal history you are moved to county that day and killed by an old enemy in prison.")
                    time.sleep(2)
                    print("GAME OVER")
            else:#don't jump in shoulder
                print ("You decide to take the L and sit in traffic. You ended up getting rear ended by a 2001 green Camry.")
                print ("The driver has no insurance and does not speak very good English so you leave it alone because your car already has numerous dents")
                time.sleep(3)
                print ("You arrive at work feeling defeated.")
                print ("You are called into your boss' office and fired because of your poor attitude and tardiness.\n")
                print ("You leave work depressed.\n")
                print ("GAME OVER")
                
    else: #you examine wires
        print ("You lean close to the wires and accidentally touch exposed wiring with your barefoot and shock yourself.\n")
        time.sleep(2)
        print ("You drop dead immediately.")
        time.sleep(2)
        print("GAME OVER")
else:
    print("Don't be a loser, fix your life man!")


    
